# coding: utf-8

"""
    Cloudbeds API

    <p>     Welcome to the documentation for <strong>Cloudbeds API Version v1.3</strong>!     If you are looking to learn how to use the Cloudbeds API to access guest information, reservations, or similar data     for your Cloudbeds customers, then you've come to the right place. </p>  <p>     In this document you will find all the API methods we provide along with explanations for parameters and response     examples. </p>  <p>     If you have questions about different implementation steps (e.g. how to implement OAuth 2.0), please refer to our     <a href=\"https://integrations.cloudbeds.com/hc/en-us\">Integrations Portal</a>. </p>  <p>     Be sure to <a href=\"https://go.pardot.com/l/308041/2018-07-24/qb2lg\">subscribe</a> to the monthly     Cloudbeds API announcement mailing list to receive information on new additions and improvements to the     Cloudbeds API and related developer tools. </p>  <p>     <strong>Endpoint:</strong> https://api.cloudbeds.com/api/v1.3/{method} </p>  <p>     <strong>HTTPS:</strong> Our API requires HTTPS. We'll respond with an appropriate error if you're not using it. </p>  <p>     <strong>Request Format:</strong> HTTP GET, POST and PUT (Content-Type: application/x-www-form-urlencoded) </p>  <p>     <strong>Response Format:</strong> JSON </p>  <p>     <strong>Response Header:</strong> X-Request-ID is added to response headers in all calls to help accelerate support     and troubleshooting. </p>  <p>     <strong>         <a href=\"https://integrations.cloudbeds.com/hc/en-us/articles/14104678058267-API-Documentation#postman-collection\">             <img src=\"https://run.pstmn.io/button.svg\" alt=\"Run in Postman\">         </a>     </strong> use this link to access our Public collection in Postman. </p>

    The version of the OpenAPI document: v1.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PostCreateAllotmentBlockResponseDataInnerResourcesInner(BaseModel):
    """
    PostCreateAllotmentBlockResponseDataInnerResourcesInner
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Resource quote ID")
    resource_type_id: Optional[StrictStr] = Field(default=None, description="Resource type ID", alias="resourceTypeId")
    resource_id: Optional[StrictStr] = Field(default=None, description="Resource ID (null for quantity-based)", alias="resourceId")
    resource_type_quantity: Optional[StrictInt] = Field(default=None, description="Quantity of resources", alias="resourceTypeQuantity")
    start_at: Optional[StrictStr] = Field(default=None, description="Start date-time (ISO-8601)", alias="startAt")
    end_at: Optional[StrictStr] = Field(default=None, description="End date-time (ISO-8601)", alias="endAt")
    interval_rate: Optional[StrictInt] = Field(default=None, description="Rate in cents (e.g. 15000 = $150.00)", alias="intervalRate")
    interval_type: Optional[StrictStr] = Field(default=None, description="Interval type", alias="intervalType")
    confirmed: Optional[StrictBool] = Field(default=None, description="Whether the resource quote is confirmed")
    adults: Optional[StrictInt] = Field(default=None, description="Number of adults")
    children: Optional[StrictInt] = Field(default=None, description="Number of children")
    inventory_strategy: Optional[StrictStr] = Field(default=None, description="Inventory strategy", alias="inventoryStrategy")
    allotment_quantity_total: Optional[StrictInt] = Field(default=None, description="Total allotment quantity", alias="allotmentQuantityTotal")
    allotment_quantity_consumed: Optional[StrictInt] = Field(default=None, description="Consumed allotment quantity", alias="allotmentQuantityConsumed")
    resource_type: Optional[Dict[str, Any]] = Field(default=None, description="Resource type details", alias="resourceType")
    resource: Optional[Dict[str, Any]] = Field(default=None, description="Resource details")
    title: Optional[StrictStr] = Field(default=None, description="Title")
    notes: Optional[StrictStr] = Field(default=None, description="Notes")
    event_interval_period: Optional[StrictStr] = Field(default=None, description="Event interval period", alias="eventIntervalPeriod")
    event_interval_amount: Optional[StrictInt] = Field(default=None, description="Event interval amount", alias="eventIntervalAmount")
    interval_quantity: Optional[StrictInt] = Field(default=None, description="Interval quantity", alias="intervalQuantity")
    currency_code: Optional[StrictStr] = Field(default=None, description="Currency code", alias="currencyCode")
    net_amount: Optional[Dict[str, Any]] = Field(default=None, description="Net amount", alias="netAmount")
    subtotal: Optional[Dict[str, Any]] = Field(default=None, description="Subtotal")
    inclusive_taxes_and_fees_amount: Optional[Dict[str, Any]] = Field(default=None, description="Inclusive taxes and fees", alias="inclusiveTaxesAndFeesAmount")
    exclusive_taxes_and_fees_amount: Optional[Dict[str, Any]] = Field(default=None, description="Exclusive taxes and fees", alias="exclusiveTaxesAndFeesAmount")
    total: Optional[Dict[str, Any]] = Field(default=None, description="Total")
    taxes: Optional[List[Dict[str, Any]]] = Field(default=None, description="Applied taxes")
    fees: Optional[List[Dict[str, Any]]] = Field(default=None, description="Applied fees")
    __properties: ClassVar[List[str]] = ["id", "resourceTypeId", "resourceId", "resourceTypeQuantity", "startAt", "endAt", "intervalRate", "intervalType", "confirmed", "adults", "children", "inventoryStrategy", "allotmentQuantityTotal", "allotmentQuantityConsumed", "resourceType", "resource", "title", "notes", "eventIntervalPeriod", "eventIntervalAmount", "intervalQuantity", "currencyCode", "netAmount", "subtotal", "inclusiveTaxesAndFeesAmount", "exclusiveTaxesAndFeesAmount", "total", "taxes", "fees"]

    @field_validator('interval_type')
    def interval_type_validate_enum(cls, value):
        """Validates the enum, returning unknown_default_open_api for unrecognized values"""
        if value is None:
            return value

        _allowed_values = set(['per_interval', 'per_rental', 'unknown_default_open_api'])
        if value not in _allowed_values:
            return 'unknown_default_open_api'
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostCreateAllotmentBlockResponseDataInnerResourcesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if resource_id (nullable) is None
        # and model_fields_set contains the field
        if self.resource_id is None and "resource_id" in self.model_fields_set:
            _dict['resourceId'] = None

        # set to None if resource_type_quantity (nullable) is None
        # and model_fields_set contains the field
        if self.resource_type_quantity is None and "resource_type_quantity" in self.model_fields_set:
            _dict['resourceTypeQuantity'] = None

        # set to None if interval_rate (nullable) is None
        # and model_fields_set contains the field
        if self.interval_rate is None and "interval_rate" in self.model_fields_set:
            _dict['intervalRate'] = None

        # set to None if interval_type (nullable) is None
        # and model_fields_set contains the field
        if self.interval_type is None and "interval_type" in self.model_fields_set:
            _dict['intervalType'] = None

        # set to None if inventory_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.inventory_strategy is None and "inventory_strategy" in self.model_fields_set:
            _dict['inventoryStrategy'] = None

        # set to None if allotment_quantity_total (nullable) is None
        # and model_fields_set contains the field
        if self.allotment_quantity_total is None and "allotment_quantity_total" in self.model_fields_set:
            _dict['allotmentQuantityTotal'] = None

        # set to None if allotment_quantity_consumed (nullable) is None
        # and model_fields_set contains the field
        if self.allotment_quantity_consumed is None and "allotment_quantity_consumed" in self.model_fields_set:
            _dict['allotmentQuantityConsumed'] = None

        # set to None if resource_type (nullable) is None
        # and model_fields_set contains the field
        if self.resource_type is None and "resource_type" in self.model_fields_set:
            _dict['resourceType'] = None

        # set to None if resource (nullable) is None
        # and model_fields_set contains the field
        if self.resource is None and "resource" in self.model_fields_set:
            _dict['resource'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if event_interval_period (nullable) is None
        # and model_fields_set contains the field
        if self.event_interval_period is None and "event_interval_period" in self.model_fields_set:
            _dict['eventIntervalPeriod'] = None

        # set to None if event_interval_amount (nullable) is None
        # and model_fields_set contains the field
        if self.event_interval_amount is None and "event_interval_amount" in self.model_fields_set:
            _dict['eventIntervalAmount'] = None

        # set to None if interval_quantity (nullable) is None
        # and model_fields_set contains the field
        if self.interval_quantity is None and "interval_quantity" in self.model_fields_set:
            _dict['intervalQuantity'] = None

        # set to None if currency_code (nullable) is None
        # and model_fields_set contains the field
        if self.currency_code is None and "currency_code" in self.model_fields_set:
            _dict['currencyCode'] = None

        # set to None if net_amount (nullable) is None
        # and model_fields_set contains the field
        if self.net_amount is None and "net_amount" in self.model_fields_set:
            _dict['netAmount'] = None

        # set to None if subtotal (nullable) is None
        # and model_fields_set contains the field
        if self.subtotal is None and "subtotal" in self.model_fields_set:
            _dict['subtotal'] = None

        # set to None if inclusive_taxes_and_fees_amount (nullable) is None
        # and model_fields_set contains the field
        if self.inclusive_taxes_and_fees_amount is None and "inclusive_taxes_and_fees_amount" in self.model_fields_set:
            _dict['inclusiveTaxesAndFeesAmount'] = None

        # set to None if exclusive_taxes_and_fees_amount (nullable) is None
        # and model_fields_set contains the field
        if self.exclusive_taxes_and_fees_amount is None and "exclusive_taxes_and_fees_amount" in self.model_fields_set:
            _dict['exclusiveTaxesAndFeesAmount'] = None

        # set to None if total (nullable) is None
        # and model_fields_set contains the field
        if self.total is None and "total" in self.model_fields_set:
            _dict['total'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostCreateAllotmentBlockResponseDataInnerResourcesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "resourceTypeId": obj.get("resourceTypeId"),
            "resourceId": obj.get("resourceId"),
            "resourceTypeQuantity": obj.get("resourceTypeQuantity"),
            "startAt": obj.get("startAt"),
            "endAt": obj.get("endAt"),
            "intervalRate": obj.get("intervalRate"),
            "intervalType": obj.get("intervalType"),
            "confirmed": obj.get("confirmed"),
            "adults": obj.get("adults"),
            "children": obj.get("children"),
            "inventoryStrategy": obj.get("inventoryStrategy"),
            "allotmentQuantityTotal": obj.get("allotmentQuantityTotal"),
            "allotmentQuantityConsumed": obj.get("allotmentQuantityConsumed"),
            "resourceType": obj.get("resourceType"),
            "resource": obj.get("resource"),
            "title": obj.get("title"),
            "notes": obj.get("notes"),
            "eventIntervalPeriod": obj.get("eventIntervalPeriod"),
            "eventIntervalAmount": obj.get("eventIntervalAmount"),
            "intervalQuantity": obj.get("intervalQuantity"),
            "currencyCode": obj.get("currencyCode"),
            "netAmount": obj.get("netAmount"),
            "subtotal": obj.get("subtotal"),
            "inclusiveTaxesAndFeesAmount": obj.get("inclusiveTaxesAndFeesAmount"),
            "exclusiveTaxesAndFeesAmount": obj.get("exclusiveTaxesAndFeesAmount"),
            "total": obj.get("total"),
            "taxes": obj.get("taxes"),
            "fees": obj.get("fees")
        })
        return _obj


