# coding: utf-8

"""
    Cloudbeds API

    <p>     Welcome to the documentation for <strong>Cloudbeds API Version v1.3</strong>!     If you are looking to learn how to use the Cloudbeds API to access guest information, reservations, or similar data     for your Cloudbeds customers, then you've come to the right place. </p>  <p>     In this document you will find all the API methods we provide along with explanations for parameters and response     examples. </p>  <p>     If you have questions about different implementation steps (e.g. how to implement OAuth 2.0), please refer to our     <a href=\"https://integrations.cloudbeds.com/hc/en-us\">Integrations Portal</a>. </p>  <p>     Be sure to <a href=\"https://go.pardot.com/l/308041/2018-07-24/qb2lg\">subscribe</a> to the monthly     Cloudbeds API announcement mailing list to receive information on new additions and improvements to the     Cloudbeds API and related developer tools. </p>  <p>     <strong>Endpoint:</strong> https://api.cloudbeds.com/api/v1.3/{method} </p>  <p>     <strong>HTTPS:</strong> Our API requires HTTPS. We'll respond with an appropriate error if you're not using it. </p>  <p>     <strong>Request Format:</strong> HTTP GET, POST and PUT (Content-Type: application/x-www-form-urlencoded) </p>  <p>     <strong>Response Format:</strong> JSON </p>  <p>     <strong>Response Header:</strong> X-Request-ID is added to response headers in all calls to help accelerate support     and troubleshooting. </p>  <p>     <strong>         <a href=\"https://integrations.cloudbeds.com/hc/en-us/articles/14104678058267-API-Documentation#postman-collection\">             <img src=\"https://run.pstmn.io/button.svg\" alt=\"Run in Postman\">         </a>     </strong> use this link to access our Public collection in Postman. </p>

    The version of the OpenAPI document: v1.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from cloudbeds_pms.models.get_taxes_and_fees_response_data_inner_length_of_stay_settings_one_of_ranges_inner_amount import GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmount
from cloudbeds_pms.models.get_taxes_and_fees_response_data_inner_length_of_stay_settings_one_of_ranges_inner_amount_adult import GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmountAdult
from cloudbeds_pms.models.get_taxes_and_fees_response_data_inner_length_of_stay_settings_one_of_ranges_inner_amount_child import GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmountChild
from cloudbeds_pms.models.get_taxes_and_fees_response_data_inner_length_of_stay_settings_one_of_ranges_inner_amount_rate_based_inner import GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmountRateBasedInner
from cloudbeds_pms.models.get_taxes_and_fees_response_data_inner_length_of_stay_settings_one_of_ranges_inner_maximum_nights import GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerMaximumNights
from cloudbeds_pms.models.get_taxes_and_fees_response_data_inner_length_of_stay_settings_one_of_ranges_inner_minimum_nights import GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerMinimumNights
from typing import Optional, Set
from typing_extensions import Self

class GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInner(BaseModel):
    """
    GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInner
    """ # noqa: E501
    minimum_nights: Optional[GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerMinimumNights] = Field(default=None, alias="minimumNights")
    maximum_nights: Optional[GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerMaximumNights] = Field(default=None, alias="maximumNights")
    amount: Optional[GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmount] = None
    amount_adult: Optional[GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmountAdult] = Field(default=None, alias="amountAdult")
    amount_child: Optional[GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmountChild] = Field(default=None, alias="amountChild")
    amount_rate_based: Optional[List[GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmountRateBasedInner]] = Field(default=None, description="Rate-based amounts for this range (uses same amountType as the parent tax/fee)", alias="amountRateBased")
    __properties: ClassVar[List[str]] = ["minimumNights", "maximumNights", "amount", "amountAdult", "amountChild", "amountRateBased"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of minimum_nights
        if self.minimum_nights:
            _dict['minimumNights'] = self.minimum_nights.to_dict()
        # override the default output from pydantic by calling `to_dict()` of maximum_nights
        if self.maximum_nights:
            _dict['maximumNights'] = self.maximum_nights.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_adult
        if self.amount_adult:
            _dict['amountAdult'] = self.amount_adult.to_dict()
        # override the default output from pydantic by calling `to_dict()` of amount_child
        if self.amount_child:
            _dict['amountChild'] = self.amount_child.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in amount_rate_based (list)
        _items = []
        if self.amount_rate_based:
            for _item_amount_rate_based in self.amount_rate_based:
                if _item_amount_rate_based:
                    _items.append(_item_amount_rate_based.to_dict())
            _dict['amountRateBased'] = _items
        # set to None if maximum_nights (nullable) is None
        # and model_fields_set contains the field
        if self.maximum_nights is None and "maximum_nights" in self.model_fields_set:
            _dict['maximumNights'] = None

        # set to None if amount (nullable) is None
        # and model_fields_set contains the field
        if self.amount is None and "amount" in self.model_fields_set:
            _dict['amount'] = None

        # set to None if amount_adult (nullable) is None
        # and model_fields_set contains the field
        if self.amount_adult is None and "amount_adult" in self.model_fields_set:
            _dict['amountAdult'] = None

        # set to None if amount_child (nullable) is None
        # and model_fields_set contains the field
        if self.amount_child is None and "amount_child" in self.model_fields_set:
            _dict['amountChild'] = None

        # set to None if amount_rate_based (nullable) is None
        # and model_fields_set contains the field
        if self.amount_rate_based is None and "amount_rate_based" in self.model_fields_set:
            _dict['amountRateBased'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "minimumNights": GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerMinimumNights.from_dict(obj["minimumNights"]) if obj.get("minimumNights") is not None else None,
            "maximumNights": GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerMaximumNights.from_dict(obj["maximumNights"]) if obj.get("maximumNights") is not None else None,
            "amount": GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmount.from_dict(obj["amount"]) if obj.get("amount") is not None else None,
            "amountAdult": GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmountAdult.from_dict(obj["amountAdult"]) if obj.get("amountAdult") is not None else None,
            "amountChild": GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmountChild.from_dict(obj["amountChild"]) if obj.get("amountChild") is not None else None,
            "amountRateBased": [GetTaxesAndFeesResponseDataInnerLengthOfStaySettingsOneOfRangesInnerAmountRateBasedInner.from_dict(_item) for _item in obj["amountRateBased"]] if obj.get("amountRateBased") is not None else None
        })
        return _obj


