# coding: utf-8

"""
    Cloudbeds API v2

    <p>Welcome to the documentation for <strong>Cloudbeds API Version v2</strong>! If you are looking to learn how to use the Cloudbeds API to access guest information, reservations, or similar data for your Cloudbeds customers, then you've come to the right place.</p><p>In this document you will find all the API methods we provide along with explanations for parameters and response examples.</p><p>If you have questions about different implementation steps (e.g. how to implement OAuth 2.0), please refer to our <a href='https://integrations.cloudbeds.com/hc/en-us'>Integrations Portal</a>.</p><p>Be sure to <a href='https://go.pardot.com/l/308041/2018-07-24/qb2lg'>subscribe</a> to the monthly Cloudbeds API announcement mailing list to receive information on new additions and improvements to the Cloudbeds API and related developer tools.</p><p><strong>Endpoint:</strong> https://api.cloudbeds.com/{method}</p><p><strong>HTTPS:</strong> Our API requires HTTPS. We'll respond with an appropriate error if you're not using it.</p><p><strong>Request Format:</strong> HTTP GET, POST and PUT (Content-Type: application/x-www-form-urlencoded)</p><p><strong>Response Format:</strong> JSON</p><p><strong>Response Header:</strong> X-Request-ID is added to response headers in all calls to help accelerate support and troubleshooting.</p><p><strong><a href='https://integrations.cloudbeds.com/hc/en-us/articles/14104678058267-API-Documentation#postman-collection'><img src='https://run.pstmn.io/button.svg' alt='Run in Postman'></a></strong> use this link to access our Public collection in Postman.</p>

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PolicyExceptionIntervalSchema(BaseModel):
    """
    PolicyExceptionIntervalSchema
    """ # noqa: E501
    start_date: date = Field(description="Start date of the interval.", alias="startDate")
    end_date: date = Field(description="End date of the interval.", alias="endDate")
    day0: Optional[StrictBool] = Field(default=None, description="Sunday (day 0) -- apply exception on this day of the week.")
    day1: Optional[StrictBool] = Field(default=None, description="Monday (day 1) -- apply exception on this day of the week.")
    day2: Optional[StrictBool] = Field(default=None, description="Tuesday (day 2) -- apply exception on this day of the week.")
    day3: Optional[StrictBool] = Field(default=None, description="Wednesday (day 3) -- apply exception on this day of the week.")
    day4: Optional[StrictBool] = Field(default=None, description="Thursday (day 4) -- apply exception on this day of the week.")
    day5: Optional[StrictBool] = Field(default=None, description="Friday (day 5) -- apply exception on this day of the week.")
    day6: Optional[StrictBool] = Field(default=None, description="Saturday (day 6) -- apply exception on this day of the week.")
    __properties: ClassVar[List[str]] = ["startDate", "endDate", "day0", "day1", "day2", "day3", "day4", "day5", "day6"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PolicyExceptionIntervalSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PolicyExceptionIntervalSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "startDate": obj.get("startDate"),
            "endDate": obj.get("endDate"),
            "day0": obj.get("day0"),
            "day1": obj.get("day1"),
            "day2": obj.get("day2"),
            "day3": obj.get("day3"),
            "day4": obj.get("day4"),
            "day5": obj.get("day5"),
            "day6": obj.get("day6")
        })
        return _obj


